"use client";

import * as React from "react";
import {
  CaretSortIcon,
  ChevronDownIcon,
  DotsHorizontalIcon,
} from "@radix-ui/react-icons";
import {
  ColumnDef,
  ColumnFiltersState,
  SortingState,
  VisibilityState,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
} from "@tanstack/react-table";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const data: Holding[] = [
  {
    ticker: "TWD",
    name: "TWD CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "10,285,856.35",
    weight: 1.76,
    notionalValue: "10,285,856.35",
    shares: "321,294,152.00",
    price: 3.2,
    location: "Taiwan",
    exchange: "-",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: "ATO",
    name: "ATOS",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "6,847,396.37",
    weight: 1.17,
    notionalValue: "6,847,396.37",
    shares: "798,510.00",
    price: 8.58,
    location: "France",
    exchange: "Nyse Euronext - Euronext Paris",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "SNAP",
    name: "SNAP INC CLASS A",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "6,365,625.48",
    weight: 1.09,
    notionalValue: "6,365,625.48",
    shares: "376,219.00",
    price: 16.92,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "SLAB",
    name: "SILICON LABORATORIES INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "6,334,549.30",
    weight: 1.09,
    notionalValue: "6,334,549.30",
    shares: "47,521.00",
    price: 133.3,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "LUMN",
    name: "LUMEN TECHNOLOGIES INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "6,268,165.75",
    weight: 1.08,
    notionalValue: "6,268,165.75",
    shares: "3,463,075.00",
    price: 1.81,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AUTO",
    name: "AUTOSTORE HOLDINGS LTD",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "6,200,651.37",
    weight: 1.06,
    notionalValue: "6,200,651.37",
    shares: "3,183,229.00",
    price: 1.95,
    location: "Norway",
    exchange: "Oslo Bors Asa",
    currency: "USD",
    fxRate: 10.47,
    marketCurrency: "NOK",
    accrualDate: "-",
  },
  {
    ticker: "LSCC",
    name: "LATTICE SEMICONDUCTOR CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,922,896.70",
    weight: 1.02,
    notionalValue: "5,922,896.70",
    shares: "85,038.00",
    price: 69.65,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "DOCN",
    name: "DIGITALOCEAN HOLDINGS INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,912,316.95",
    weight: 1.01,
    notionalValue: "5,912,316.95",
    shares: "166,685.00",
    price: 35.47,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AYX",
    name: "ALTERYX INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,894,748.20",
    weight: 1.01,
    notionalValue: "5,894,748.20",
    shares: "122,705.00",
    price: 48.04,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AMD",
    name: "ADVANCED MICRO DEVICES INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,893,837.40",
    weight: 1.01,
    notionalValue: "5,893,837.40",
    shares: "42,356.00",
    price: 139.15,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ADSK",
    name: "AUTODESK INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,852,999.53",
    weight: 1,
    notionalValue: "5,852,999.53",
    shares: "24,157.00",
    price: 242.29,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "FRSH",
    name: "FRESHWORKS INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,789,310.45",
    weight: 0.99,
    notionalValue: "5,789,310.45",
    shares: "239,723.00",
    price: 24.15,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "DDD",
    name: "3D SYSTEMS CORP",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,782,146.91",
    weight: 0.99,
    notionalValue: "5,782,146.91",
    shares: "902,051.00",
    price: 6.41,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AMBA",
    name: "AMBARELLA INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,752,268.67",
    weight: 0.99,
    notionalValue: "5,752,268.67",
    shares: "89,781.00",
    price: 64.07,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "INFA",
    name: "INFORMATICA INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,743,140.48",
    weight: 0.99,
    notionalValue: "5,743,140.48",
    shares: "198,176.00",
    price: 28.98,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "PINS",
    name: "PINTEREST INC CLASS A",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,740,256.22",
    weight: 0.98,
    notionalValue: "5,740,256.22",
    shares: "153,606.00",
    price: 37.37,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "BMBL",
    name: "BUMBLE INC CLASS A",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,682,468.28",
    weight: 0.97,
    notionalValue: "5,682,468.28",
    shares: "374,833.00",
    price: 15.16,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "HUBS",
    name: "HUBSPOT INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,667,550.64",
    weight: 0.97,
    notionalValue: "5,667,550.64",
    shares: "10,162.00",
    price: 557.72,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "CGNX",
    name: "COGNEX CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,663,504.24",
    weight: 0.97,
    notionalValue: "5,663,504.24",
    shares: "135,361.00",
    price: 41.84,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "SIRI",
    name: "SIRIUS XM HOLDINGS INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,659,011.00",
    weight: 0.97,
    notionalValue: "5,659,011.00",
    shares: "1,047,965.00",
    price: 5.4,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "CEVA",
    name: "CEVA INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,658,947.25",
    weight: 0.97,
    notionalValue: "5,658,947.25",
    shares: "240,295.00",
    price: 23.55,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "SPOT",
    name: "SPOTIFY TECHNOLOGY SA",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,658,061.31",
    weight: 0.97,
    notionalValue: "5,658,061.31",
    shares: "29,443.00",
    price: 192.17,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 3443,
    name: "GLOBAL UNICHIP CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,650,440.99",
    weight: 0.97,
    notionalValue: "5,650,440.99",
    shares: "100,000.00",
    price: 56.5,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: "ARM",
    name: "ARM HOLDINGS AMERICAN DEPOSITARY S",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,645,109.25",
    weight: 0.97,
    notionalValue: "5,645,109.25",
    shares: "79,475.00",
    price: 71.03,
    location: "United Kingdom",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 3661,
    name: "ALCHIP TECHNOLOGIES LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,616,506.33",
    weight: 0.96,
    notionalValue: "5,616,506.33",
    shares: "51,000.00",
    price: 110.13,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: "SNOW",
    name: "SNOWFLAKE CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,605,116.65",
    weight: 0.96,
    notionalValue: "5,605,116.65",
    shares: "28,165.00",
    price: 199.01,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "QCOM",
    name: "QUALCOMM INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,577,060.45",
    weight: 0.96,
    notionalValue: "5,577,060.45",
    shares: "38,965.00",
    price: 143.13,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "MTRN",
    name: "MAYTRONICS LTD",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,561,409.07",
    weight: 0.95,
    notionalValue: "5,561,409.07",
    shares: "516,141.00",
    price: 10.77,
    location: "Israel",
    exchange: "Tel Aviv Stock exchange",
    currency: "USD",
    fxRate: 3.67,
    marketCurrency: "ILS",
    accrualDate: "-",
  },
  {
    ticker: 6758,
    name: "SONY GROUP CORP",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,543,804.45",
    weight: 0.95,
    notionalValue: "5,543,804.45",
    shares: "58,800.00",
    price: 94.28,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "YY",
    name: "JOYY ADR INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,543,208.20",
    weight: 0.95,
    notionalValue: "5,543,208.20",
    shares: "143,830.00",
    price: 38.54,
    location: "China",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "MOMO",
    name: "HELLO GROUP ADR INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,529,066.56",
    weight: 0.95,
    notionalValue: "5,529,066.56",
    shares: "772,216.00",
    price: 7.16,
    location: "China",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "META",
    name: "META PLATFORMS INC CLASS A",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,514,122.88",
    weight: 0.95,
    notionalValue: "5,514,122.88",
    shares: "16,464.00",
    price: 334.92,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 2018,
    name: "AAC TECHNOLOGIES HOLDINGS INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,507,543.87",
    weight: 0.94,
    notionalValue: "5,507,543.87",
    shares: "1,806,000.00",
    price: 3.05,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "SSYS",
    name: "STRATASYS LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,496,272.88",
    weight: 0.94,
    notionalValue: "5,496,272.88",
    shares: "435,176.00",
    price: 12.63,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "MSTR",
    name: "MICROSTRATEGY INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,482,210.51",
    weight: 0.94,
    notionalValue: "5,482,210.51",
    shares: "9,611.00",
    price: 570.41,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "CLVT",
    name: "CLARIVATE PLC",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,468,602.50",
    weight: 0.94,
    notionalValue: "5,468,602.50",
    shares: "643,365.00",
    price: 8.5,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ADI",
    name: "ANALOG DEVICES INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,461,525.44",
    weight: 0.94,
    notionalValue: "5,461,525.44",
    shares: "27,188.00",
    price: 200.88,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "FUBO",
    name: "FUBOTV INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,431,181.28",
    weight: 0.93,
    notionalValue: "5,431,181.28",
    shares: "1,616,423.00",
    price: 3.36,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "GENI",
    name: "GENIUS SPORTS LTD",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,425,745.50",
    weight: 0.93,
    notionalValue: "5,425,745.50",
    shares: "911,890.00",
    price: 5.95,
    location: "United Kingdom",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "MCHP",
    name: "MICROCHIP TECHNOLOGY INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,417,026.60",
    weight: 0.93,
    notionalValue: "5,417,026.60",
    shares: "58,753.00",
    price: 92.2,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "TXN",
    name: "TEXAS INSTRUMENT INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,408,622.08",
    weight: 0.93,
    notionalValue: "5,408,622.08",
    shares: "32,072.00",
    price: 168.64,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 277810,
    name: "RAINBOW ROBOTICS",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,406,335.76",
    weight: 0.93,
    notionalValue: "5,406,335.76",
    shares: "38,724.00",
    price: 139.61,
    location: "Korea (South)",
    exchange: "Korea exchange (Kosdaq)",
    currency: "USD",
    fxRate: "1,296.45",
    marketCurrency: "KRW",
    accrualDate: "-",
  },
  {
    ticker: "NVDA",
    name: "NVIDIA CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,405,767.30",
    weight: 0.93,
    notionalValue: "5,405,767.30",
    shares: "11,057.00",
    price: 488.9,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "IQ",
    name: "IQIYI ADS REPRESENTING INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,401,183.32",
    weight: 0.93,
    notionalValue: "5,401,183.32",
    shares: "1,154,099.00",
    price: 4.68,
    location: "China",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 6506,
    name: "YASKAWA ELECTRIC CORP",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,397,837.82",
    weight: 0.93,
    notionalValue: "5,397,837.82",
    shares: "134,500.00",
    price: 40.13,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "IFX",
    name: "INFINEON TECHNOLOGIES AG",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,387,017.89",
    weight: 0.92,
    notionalValue: "5,387,017.89",
    shares: "126,820.00",
    price: 42.48,
    location: "Germany",
    exchange: "Xetra",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "GOOGL",
    name: "ALPHABET INC CLASS A",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,375,338.80",
    weight: 0.92,
    notionalValue: "5,375,338.80",
    shares: "40,538.00",
    price: 132.6,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ABBN",
    name: "ABB LTD",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,366,708.08",
    weight: 0.92,
    notionalValue: "5,366,708.08",
    shares: "123,170.00",
    price: 43.57,
    location: "Switzerland",
    exchange: "SIX Swiss exchange",
    currency: "USD",
    fxRate: 0.87,
    marketCurrency: "CHF",
    accrualDate: "-",
  },
  {
    ticker: "STLAM",
    name: "STELLANTIS NV",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,362,941.62",
    weight: 0.92,
    notionalValue: "5,362,941.62",
    shares: "228,041.00",
    price: 23.52,
    location: "Italy",
    exchange: "Borsa Italiana",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "ALTR",
    name: "ALTAIR ENGINEERING INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,356,686.16",
    weight: 0.92,
    notionalValue: "5,356,686.16",
    shares: "72,212.00",
    price: 74.18,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "STMPA",
    name: "STMICROELECTRONICS NV",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,354,098.19",
    weight: 0.92,
    notionalValue: "5,354,098.19",
    shares: "104,775.00",
    price: 51.1,
    location: "France",
    exchange: "Nyse Euronext - Euronext Paris",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "PARA",
    name: "PARAMOUNT GLOBAL CLASS B",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,353,399.45",
    weight: 0.92,
    notionalValue: "5,353,399.45",
    shares: "329,035.00",
    price: 16.27,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 6479,
    name: "MINEBEA MITSUMI INC",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,328,271.31",
    weight: 0.91,
    notionalValue: "5,328,271.31",
    shares: "265,300.00",
    price: 20.08,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "INTC",
    name: "INTEL CORPORATION CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,303,414.72",
    weight: 0.91,
    notionalValue: "5,303,414.72",
    shares: "114,892.00",
    price: 46.16,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ATS",
    name: "ATS CORP",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,283,618.08",
    weight: 0.91,
    notionalValue: "5,283,618.08",
    shares: "123,591.00",
    price: 42.75,
    location: "Canada",
    exchange: "Toronto Stock exchange",
    currency: "USD",
    fxRate: 1.34,
    marketCurrency: "CAD",
    accrualDate: "-",
  },
  {
    ticker: 6526,
    name: "AIROHA TECHNOLOGY CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,273,638.21",
    weight: 0.9,
    notionalValue: "5,273,638.21",
    shares: "285,000.00",
    price: 18.5,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: 136,
    name: "CHINA RUYI HOLDINGS LTD",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,261,065.94",
    weight: 0.9,
    notionalValue: "5,261,065.94",
    shares: "21,840,000.00",
    price: 0.24,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: 6954,
    name: "FANUC CORP",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,252,034.14",
    weight: 0.9,
    notionalValue: "5,252,034.14",
    shares: "181,100.00",
    price: 29,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "DUE",
    name: "DUERR AG",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,251,430.33",
    weight: 0.9,
    notionalValue: "5,251,430.33",
    shares: "231,743.00",
    price: 22.66,
    location: "Germany",
    exchange: "Xetra",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "DBX",
    name: "DROPBOX INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,249,819.18",
    weight: 0.9,
    notionalValue: "5,249,819.18",
    shares: "177,239.00",
    price: 29.62,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 6594,
    name: "NIDEC CORP",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,234,992.77",
    weight: 0.9,
    notionalValue: "5,234,992.77",
    shares: "132,800.00",
    price: 39.42,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "IRBT",
    name: "IROBOT CORP",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,233,932.04",
    weight: 0.9,
    notionalValue: "5,233,932.04",
    shares: "138,997.00",
    price: 37.66,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 6971,
    name: "KYOCERA CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,230,870.16",
    weight: 0.9,
    notionalValue: "5,230,870.16",
    shares: "91,600.00",
    price: 57.11,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "ISRG",
    name: "INTUITIVE SURGICAL INC",
    sector: "Health Care",
    assetClass: "Equity",
    marketValue: "5,227,224.60",
    weight: 0.9,
    notionalValue: "5,227,224.60",
    shares: "16,116.00",
    price: 324.35,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ESTC",
    name: "ELASTIC NV",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,208,013.27",
    weight: 0.89,
    notionalValue: "5,208,013.27",
    shares: "46,199.00",
    price: 112.73,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "PRLB",
    name: "PROTO LABS INC",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,201,876.26",
    weight: 0.89,
    notionalValue: "5,201,876.26",
    shares: "137,543.00",
    price: 37.82,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 1810,
    name: "XIAOMI CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,197,567.00",
    weight: 0.89,
    notionalValue: "5,197,567.00",
    shares: "2,538,400.00",
    price: 2.05,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "NNDM",
    name: "NANO DIMENSION SPONSORED ADR REPR",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,191,020.25",
    weight: 0.89,
    notionalValue: "5,191,020.25",
    shares: "2,171,975.00",
    price: 2.39,
    location: "Israel",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AME",
    name: "AMETEK INC",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,186,881.48",
    weight: 0.89,
    notionalValue: "5,186,881.48",
    shares: "31,796.00",
    price: 163.13,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 4716,
    name: "ORACLE JAPAN CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,183,027.05",
    weight: 0.89,
    notionalValue: "5,183,027.05",
    shares: "65,600.00",
    price: 79.01,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "SPLK",
    name: "SPLUNK INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,170,258.40",
    weight: 0.89,
    notionalValue: "5,170,258.40",
    shares: "33,890.00",
    price: 152.56,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "GDDY",
    name: "GODADDY INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,159,848.32",
    weight: 0.89,
    notionalValue: "5,159,848.32",
    shares: "49,104.00",
    price: 105.08,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 2049,
    name: "HIWIN TECHNOLOGIES CORP",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,156,684.26",
    weight: 0.88,
    notionalValue: "5,156,684.26",
    shares: "703,392.00",
    price: 7.33,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: "MTTR",
    name: "MATTERPORT INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,153,963.76",
    weight: 0.88,
    notionalValue: "5,153,963.76",
    shares: "1,952,259.00",
    price: 2.64,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "MVIS",
    name: "MICROVISION INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,152,310.33",
    weight: 0.88,
    notionalValue: "5,152,310.33",
    shares: "1,915,357.00",
    price: 2.69,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AMZN",
    name: "AMAZON COM INC",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,151,319.53",
    weight: 0.88,
    notionalValue: "5,151,319.53",
    shares: "34,349.00",
    price: 149.97,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AAPL",
    name: "APPLE INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,143,734.95",
    weight: 0.88,
    notionalValue: "5,143,734.95",
    shares: "26,035.00",
    price: 197.57,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 700,
    name: "TENCENT HOLDINGS LTD",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,140,394.78",
    weight: 0.88,
    notionalValue: "5,140,394.78",
    shares: "127,600.00",
    price: 40.29,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: 6324,
    name: "HARMONIC DRIVE SYSTEMS INC",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "5,135,917.60",
    weight: 0.88,
    notionalValue: "5,135,917.60",
    shares: "174,800.00",
    price: 29.38,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: 763,
    name: "ZTE CORP H",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,132,168.60",
    weight: 0.88,
    notionalValue: "5,132,168.60",
    shares: "2,294,000.00",
    price: 2.24,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "PTON",
    name: "PELOTON INTERACTIVE CLASS A INC",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,116,031.25",
    weight: 0.88,
    notionalValue: "5,116,031.25",
    shares: "831,875.00",
    price: 6.15,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "DSY",
    name: "DASSAULT SYSTEMES",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,115,309.60",
    weight: 0.88,
    notionalValue: "5,115,309.60",
    shares: "105,809.00",
    price: 48.34,
    location: "France",
    exchange: "Nyse Euronext - Euronext Paris",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "MP1",
    name: "MEGAPORT LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,114,979.93",
    weight: 0.88,
    notionalValue: "5,114,979.93",
    shares: "799,357.00",
    price: 6.4,
    location: "Australia",
    exchange: "Asx - All Markets",
    currency: "USD",
    fxRate: 1.49,
    marketCurrency: "AUD",
    accrualDate: "-",
  },
  {
    ticker: "NFLX",
    name: "NETFLIX INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,113,353.92",
    weight: 0.88,
    notionalValue: "5,113,353.92",
    shares: "10,832.00",
    price: 472.06,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 1357,
    name: "MEITU INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "5,112,022.14",
    weight: 0.88,
    notionalValue: "5,112,022.14",
    shares: "10,554,500.00",
    price: 0.48,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "ANSS",
    name: "ANSYS INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,106,017.07",
    weight: 0.88,
    notionalValue: "5,106,017.07",
    shares: "17,281.00",
    price: 295.47,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 2498,
    name: "HTC CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,093,579.63",
    weight: 0.87,
    notionalValue: "5,093,579.63",
    shares: "3,132,000.00",
    price: 1.63,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: 2344,
    name: "WINBOND ELECTRONICS CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,072,808.49",
    weight: 0.87,
    notionalValue: "5,072,808.49",
    shares: "5,550,150.00",
    price: 0.91,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: "CRM",
    name: "SALESFORCE INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,057,774.40",
    weight: 0.87,
    notionalValue: "5,057,774.40",
    shares: "19,334.00",
    price: 261.6,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 9988,
    name: "ALIBABA GROUP HOLDING LTD",
    sector: "Consumer Discretionary",
    assetClass: "Equity",
    marketValue: "5,035,656.40",
    weight: 0.86,
    notionalValue: "5,035,656.40",
    shares: "548,500.00",
    price: 9.18,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "005930",
    name: "SAMSUNG ELECTRONICS LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "5,031,858.85",
    weight: 0.86,
    notionalValue: "5,031,858.85",
    shares: "88,998.00",
    price: 56.54,
    location: "Korea (South)",
    exchange: "Korea exchange (Stock Market)",
    currency: "USD",
    fxRate: "1,296.45",
    marketCurrency: "KRW",
    accrualDate: "-",
  },
  {
    ticker: "MSFT",
    name: "MICROSOFT CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,929,226.08",
    weight: 0.85,
    notionalValue: "4,929,226.08",
    shares: "13,296.00",
    price: 370.73,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "BSY",
    name: "BENTLEY SYSTEMS INC CLASS B",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,899,324.75",
    weight: 0.84,
    notionalValue: "4,899,324.75",
    shares: "97,499.00",
    price: 50.25,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 3035,
    name: "FARADAY TECHNOLOGY CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,865,493.89",
    weight: 0.83,
    notionalValue: "4,865,493.89",
    shares: "421,000.00",
    price: 11.56,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: 1024,
    name: "KUAISHOU TECHNOLOGY",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "4,861,965.44",
    weight: 0.83,
    notionalValue: "4,861,965.44",
    shares: "687,400.00",
    price: 7.07,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "018260",
    name: "SAMSUNG SDS LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,833,472.33",
    weight: 0.83,
    notionalValue: "4,833,472.33",
    shares: "38,024.00",
    price: 127.12,
    location: "Korea (South)",
    exchange: "Korea exchange (Stock Market)",
    currency: "USD",
    fxRate: "1,296.45",
    marketCurrency: "KRW",
    accrualDate: "-",
  },
  {
    ticker: "PEGA",
    name: "PEGASYSTEMS INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,818,744.30",
    weight: 0.83,
    notionalValue: "4,818,744.30",
    shares: "96,510.00",
    price: 49.93,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 9888,
    name: "BAIDU CLASS A INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "4,807,565.01",
    weight: 0.82,
    notionalValue: "4,807,565.01",
    shares: "336,200.00",
    price: 14.3,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "SYM",
    name: "SYMBOTIC CORP CLASS A",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "4,804,012.15",
    weight: 0.82,
    notionalValue: "4,804,012.15",
    shares: "89,845.00",
    price: 53.47,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ADBE",
    name: "ADOBE INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,782,682.40",
    weight: 0.82,
    notionalValue: "4,782,682.40",
    shares: "8,180.00",
    price: 584.68,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 4919,
    name: "NUVOTON TECHNOLOGY CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,744,161.48",
    weight: 0.81,
    notionalValue: "4,744,161.48",
    shares: "1,051,000.00",
    price: 4.51,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: 7752,
    name: "RICOH LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,707,879.09",
    weight: 0.81,
    notionalValue: "4,707,879.09",
    shares: "614,800.00",
    price: 7.66,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: 9999,
    name: "NETEASE INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "4,618,711.36",
    weight: 0.79,
    notionalValue: "4,618,711.36",
    shares: "220,600.00",
    price: 20.94,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: 5253,
    name: "COVER CORP",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "4,607,419.14",
    weight: 0.79,
    notionalValue: "4,607,419.14",
    shares: "235,700.00",
    price: 19.55,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: 3896,
    name: "KINGSOFT CLOUD HOLDINGS LTD",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,603,217.44",
    weight: 0.79,
    notionalValue: "4,603,217.44",
    shares: "16,632,000.00",
    price: 0.28,
    location: "China",
    exchange: "Hong Kong Exchanges And Clearing Ltd",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
  {
    ticker: "TDC",
    name: "TERADATA CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,595,921.22",
    weight: 0.79,
    notionalValue: "4,595,921.22",
    shares: "107,206.00",
    price: 42.87,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 7012,
    name: "KAWASAKI HEAVY INDUSTRIES LTD",
    sector: "Industrials",
    assetClass: "Equity",
    marketValue: "4,557,625.48",
    weight: 0.78,
    notionalValue: "4,557,625.48",
    shares: "219,900.00",
    price: 20.73,
    location: "Japan",
    exchange: "Tokyo Stock exchange",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "POLICYBZR",
    name: "PB FINTECH LTD",
    sector: "Financials",
    assetClass: "Equity",
    marketValue: "4,499,021.57",
    weight: 0.77,
    notionalValue: "4,499,021.57",
    shares: "473,057.00",
    price: 9.51,
    location: "India",
    exchange: "National Stock exchange Of India",
    currency: "USD",
    fxRate: 83,
    marketCurrency: "INR",
    accrualDate: "-",
  },
  {
    ticker: "ORCL",
    name: "ORACLE CORP",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,382,317.80",
    weight: 0.75,
    notionalValue: "4,382,317.80",
    shares: "42,415.00",
    price: 103.32,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: 2388,
    name: "VIA TECHNOLOGIES INC",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "4,364,893.63",
    weight: 0.75,
    notionalValue: "4,364,893.63",
    shares: "874,000.00",
    price: 4.99,
    location: "Taiwan",
    exchange: "Taiwan Stock exchange",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "TWD",
    accrualDate: "-",
  },
  {
    ticker: "CXM",
    name: "SPRINKLR INC CLASS A",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "3,583,510.92",
    weight: 0.61,
    notionalValue: "3,583,510.92",
    shares: "319,386.00",
    price: 11.22,
    location: "United States",
    exchange: "New York Stock exchange Inc.",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "INR",
    name: "INR CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "1,740,204.12",
    weight: 0.3,
    notionalValue: "1,740,204.12",
    shares: "144,432,591.00",
    price: 1.2,
    location: "India",
    exchange: "-",
    currency: "USD",
    fxRate: 83,
    marketCurrency: "INR",
    accrualDate: "-",
  },
  {
    ticker: "AUD",
    name: "AUD CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "1,327,246.14",
    weight: 0.23,
    notionalValue: "1,327,246.14",
    shares: "1,974,628.00",
    price: 67.22,
    location: "Australia",
    exchange: "-",
    currency: "USD",
    fxRate: 1.49,
    marketCurrency: "AUD",
    accrualDate: "-",
  },
  {
    ticker: "USD",
    name: "USD CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "1,130,804.46",
    weight: 0.19,
    notionalValue: "1,130,804.46",
    shares: "1,130,804.00",
    price: 100,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "VMEO",
    name: "VIMEO INC",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "1,034,271.70",
    weight: 0.18,
    notionalValue: "1,034,271.70",
    shares: "268,642.00",
    price: 3.85,
    location: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "XTSLA",
    name: "BLK CSH FND TREASURY SL AGENCY",
    sector: "Cash and/or Derivatives",
    assetClass: "Money Market",
    marketValue: "800,000.00",
    weight: 0.14,
    notionalValue: "800,000.00",
    shares: "800,000.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "KRW",
    name: "KRW CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "608,849.77",
    weight: 0.1,
    notionalValue: "608,849.77",
    shares: "789,343,289.00",
    price: 0.08,
    location: "Korea (South)",
    exchange: "-",
    currency: "USD",
    fxRate: "1,296.45",
    marketCurrency: "KRW",
    accrualDate: "-",
  },
  {
    ticker: "067160",
    name: "AFREECATV LTD",
    sector: "Communication",
    assetClass: "Equity",
    marketValue: "273,522.93",
    weight: 0.05,
    notionalValue: "273,522.93",
    shares: "4,871.00",
    price: 56.15,
    location: "Korea (South)",
    exchange: "Korea exchange (Kosdaq)",
    currency: "USD",
    fxRate: "1,296.45",
    marketCurrency: "KRW",
    accrualDate: "-",
  },
  {
    ticker: "KC",
    name: "KINGSOFT CLOUD HOLDINGS ADR REPRES",
    sector: "Information Technology",
    assetClass: "Equity",
    marketValue: "262,048.50",
    weight: 0.04,
    notionalValue: "262,048.50",
    shares: "69,325.00",
    price: 3.78,
    location: "China",
    exchange: "NASDAQ",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "CHF",
    name: "CHF CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "175,864.66",
    weight: 0.03,
    notionalValue: "175,864.66",
    shares: "152,448.00",
    price: 115.36,
    location: "Switzerland",
    exchange: "-",
    currency: "USD",
    fxRate: 0.87,
    marketCurrency: "CHF",
    accrualDate: "-",
  },
  {
    ticker: "SEK",
    name: "SEK CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "131,037.35",
    weight: 0.02,
    notionalValue: "131,037.35",
    shares: "1,344,286.00",
    price: 9.75,
    location: "Sweden",
    exchange: "-",
    currency: "USD",
    fxRate: 10.26,
    marketCurrency: "SEK",
    accrualDate: "-",
  },
  {
    ticker: "HBCFT",
    name: "CASH COLLATERAL USD HBCFT",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash Collateral and Margins",
    marketValue: "29,000.00",
    weight: 0,
    notionalValue: "29,000.00",
    shares: "29,000.00",
    price: 100,
    location: "United Kingdom",
    exchange: "-",
    currency: "USD",
    fxRate: 1,
    marketCurrency: "USD",
    accrualDate: "May 28, 2019",
  },
  {
    ticker: "GBP",
    name: "GBP CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: 211.51,
    weight: 0,
    notionalValue: 211.51,
    shares: 167,
    price: 127,
    location: "United Kingdom",
    exchange: "-",
    currency: "USD",
    fxRate: 0.79,
    marketCurrency: "GBP",
    accrualDate: "-",
  },
  {
    ticker: "KRW",
    name: "KRW/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: 172.87,
    weight: 0,
    notionalValue: 172.87,
    shares: "-1,162,028,967.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: "1,296.45",
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "EUR",
    name: "EUR/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -20.61,
    weight: 0,
    notionalValue: -20.61,
    shares: "2,944,087.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "NOK",
    name: "NOK/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -17.29,
    weight: 0,
    notionalValue: -17.29,
    shares: "18,965,352.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 10.47,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "AUD",
    name: "AUD/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -13.51,
    weight: 0,
    notionalValue: -13.51,
    shares: "-1,929,819.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 1.49,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "ILS",
    name: "ILS/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -12.07,
    weight: 0,
    notionalValue: -12.07,
    shares: "4,054,919.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 3.67,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "CAD",
    name: "CAD/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -7.24,
    weight: 0,
    notionalValue: -7.24,
    shares: "979,381.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 1.34,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "CHF",
    name: "CHF/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -1.62,
    weight: 0,
    notionalValue: -1.62,
    shares: "-135,465.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 0.87,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "HKD",
    name: "HKD/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: -94.65,
    weight: 0,
    notionalValue: -94.65,
    shares: "73,911,838.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "TWD",
    name: "TWD/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: "-6,181.47",
    weight: 0,
    notionalValue: "-6,181.47",
    shares: "-326,213,303.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 31.24,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "INR",
    name: "INR/USD",
    sector: "Cash and/or Derivatives",
    assetClass: "FX",
    marketValue: "-6,960.61",
    weight: 0,
    notionalValue: "-6,960.61",
    shares: "-144,432,591.00",
    price: 1,
    location: "United States",
    exchange: "-",
    currency: "USD",
    fxRate: 83,
    marketCurrency: "USD",
    accrualDate: "-",
  },
  {
    ticker: "JPY",
    name: "JPY CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "-68,945.46",
    weight: -0.01,
    notionalValue: "-68,945.46",
    shares: "-9,773,363.00",
    price: 0.71,
    location: "Japan",
    exchange: "-",
    currency: "USD",
    fxRate: 141.76,
    marketCurrency: "JPY",
    accrualDate: "-",
  },
  {
    ticker: "CAD",
    name: "CAD CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "-710,927.95",
    weight: -0.12,
    notionalValue: "-710,927.95",
    shares: "-950,546.00",
    price: 74.79,
    location: "Canada",
    exchange: "-",
    currency: "USD",
    fxRate: 1.34,
    marketCurrency: "CAD",
    accrualDate: "-",
  },
  {
    ticker: "ILS",
    name: "ILS CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "-1,106,789.77",
    weight: -0.19,
    notionalValue: "-1,106,789.77",
    shares: "-4,057,381.00",
    price: 27.28,
    location: "Israel",
    exchange: "-",
    currency: "USD",
    fxRate: 3.67,
    marketCurrency: "ILS",
    accrualDate: "-",
  },
  {
    ticker: "NOK",
    name: "NOK CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "-2,019,975.03",
    weight: -0.35,
    notionalValue: "-2,019,975.03",
    shares: "-21,154,694.00",
    price: 9.55,
    location: "Norway",
    exchange: "-",
    currency: "USD",
    fxRate: 10.47,
    marketCurrency: "NOK",
    accrualDate: "-",
  },
  {
    ticker: "EUR",
    name: "EUR CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "-4,183,562.21",
    weight: -0.72,
    notionalValue: "-4,183,562.21",
    shares: "-3,832,680.00",
    price: 109.15,
    location: "European Union",
    exchange: "-",
    currency: "USD",
    fxRate: 0.92,
    marketCurrency: "EUR",
    accrualDate: "-",
  },
  {
    ticker: "HKD",
    name: "HKD CASH",
    sector: "Cash and/or Derivatives",
    assetClass: "Cash",
    marketValue: "-9,792,618.12",
    weight: -1.68,
    notionalValue: "-9,792,618.12",
    shares: "-76,425,019.00",
    price: 12.81,
    location: "Hong Kong",
    exchange: "-",
    currency: "USD",
    fxRate: 7.8,
    marketCurrency: "HKD",
    accrualDate: "-",
  },
];

export type Holding = {
  ticker: string | number;
  name: string;
  sector: string;
  assetClass: string;
  marketValue: string | number;
  weight: number;
  notionalValue: string | number;
  shares: string | number;
  price: number;
  location: string;
  exchange: string;
  currency: string;
  fxRate: number | string;
  marketCurrency: string;
  accrualDate: string;
};

const WatchlistButton = () => {
  const [isWatchlist, setIsWatchlist] = React.useState(false);

  return (
    <Button
      variant="ghost"
      onClick={() => setIsWatchlist(!isWatchlist)}
      className="ml-5 text-lg text-yellow-400 hover:text-yellow-400"
    >
      {isWatchlist ? "★" : "☆"}
    </Button>
  );
};

export const columns: ColumnDef<Holding>[] = [
  {
    id: "watchlist",
    header: () => <div className="text-center">Watchlist</div>,
    cell: () => <WatchlistButton />,
  },
  {
    accessorKey: "ticker",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
        >
          Ticker
          <CaretSortIcon className="ml-2 h-4 w-4" />
        </Button>
      );
    },
    cell: ({ row }) => (
      <div className="uppercase pl-4">{row.getValue("ticker")}</div>
    ),
  },
  {
    accessorKey: "name",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="-ml-4"
        >
          Name
          <CaretSortIcon className="ml-2 h-4 w-4" />
        </Button>
      );
    },
    cell: ({ row }) => <div>{row.getValue("name")}</div>,
  },
  {
    accessorKey: "sector",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="-ml-4"
        >
          Sector
          <CaretSortIcon className="ml-2 h-4 w-4" />
        </Button>
      );
    },
    cell: ({ row }) => <div>{row.getValue("sector")}</div>,
  },
  {
    accessorKey: "assetClass",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="-ml-4"
        >
          Asset Class
          <CaretSortIcon className="ml-2 h-4 w-4" />
        </Button>
      );
    },
    cell: ({ row }) => <div>{row.getValue("assetClass")}</div>,
  },
  {
    accessorKey: "marketValue",
    header: () => <div className="text-right pr-4">Market Value</div>,
    cell: ({ row }) => (
      <div className="text-right font-medium pr-4">
        ${row.getValue("marketValue")}
      </div>
    ),
  },
  {
    accessorKey: "weight",
    header: () => <div className="text-right pr-4">Weight</div>,
    cell: ({ row }) => (
      <div className="text-right font-medium pr-4">
        {row.getValue("weight")}%
      </div>
    ),
  },
  {
    accessorKey: "shares",
    header: () => <div className="text-right pr-4">Shares</div>,
    cell: ({ row }) => (
      <div className="text-right font-medium pr-4">
        {row.getValue("shares")}
      </div>
    ),
  },
];

export function DataTable() {
  const [sorting, setSorting] = React.useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>(
    []
  );
  const [columnVisibility, setColumnVisibility] =
    React.useState<VisibilityState>({});
  const [rowSelection, setRowSelection] = React.useState({});

  const table = useReactTable({
    data,
    columns,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    state: {
      sorting,
      columnFilters,
      columnVisibility,
      rowSelection,
    },
  });

  return (
    <div className="w-full">
      <div className="flex items-center pb-4">
        <Input
          placeholder="Filter holdings..."
          value={(table.getColumn("name")?.getFilterValue() as string) ?? ""}
          onChange={(event) =>
            table.getColumn("name")?.setFilterValue(event.target.value)
          }
          className="max-w-sm"
        />
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" className="ml-auto">
              Columns <ChevronDownIcon className="ml-2 h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {table
              .getAllColumns()
              .filter((column) => column.getCanHide())
              .map((column) => {
                return (
                  <DropdownMenuCheckboxItem
                    key={column.id}
                    className="capitalize"
                    checked={column.getIsVisible()}
                    onCheckedChange={(value) =>
                      column.toggleVisibility(!!value)
                    }
                  >
                    {column.id}
                  </DropdownMenuCheckboxItem>
                );
              })}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  return (
                    <TableHead key={header.id}>
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </TableHead>
                  );
                })}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows?.length ? (
              table.getRowModel().rows.map((row) => (
                <TableRow
                  key={row.id}
                  data-state={row.getIsSelected() && "selected"}
                >
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell
                  colSpan={columns.length}
                  className="h-24 text-center"
                >
                  No results.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
      <div className="flex items-center justify-end space-x-2 pt-4">
        {/* <div className="flex-1 text-sm text-muted-foreground">
          {table.getFilteredSelectedRowModel().rows.length} of{" "}
          {table.getFilteredRowModel().rows.length} row(s) selected.
        </div> */}
        <div className="space-x-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => table.previousPage()}
            disabled={!table.getCanPreviousPage()}
          >
            Previous
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => table.nextPage()}
            disabled={!table.getCanNextPage()}
          >
            Next
          </Button>
        </div>
      </div>
    </div>
  );
}
